name: tests

on:
  push:
    branches-ignore:
    - no-we-want-to-run-check-on-all-branches

jobs:
  tests:
    name: Unit Tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: make tests
        run: make tests
